apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tomcat-statefulset
spec:
  replicas: 2
  serviceName: "tomcat"
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: tomcat:8
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        terminationGracePeriodSeconds: 30  # Adjust as needed
  updateStrategy:
    rollingUpdate:
      partition: 0
      maxUnavailable: 1
