apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-rolling-update
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
      role: rolling-update
  template:
    metadata:
      labels:
        app: tomcat
        role: rolling-update
    spec:
      containers:
      - name: tomcat-container
        image: tomcat:9
  strategy:
    type: RollingUpdate
    rollingUp      maxSurge: 50%
